example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml , show_json, show_xml_id, show_json_id, register, login_user, logout_user, show_wishlist_ajax, show_create_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_id, name='show_xml_id'),
    path('json/<int:id>', show_json_id, name='show_json_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', show_create_wishlist, name='show_create_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
# from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Shayna Putri',
        'last_login': request.COOKIES['last_login'],
    }
    # return render(request, "wishlist.html")
    return render(request, "wishlist.html", context)

def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Shayna Putri',
        'last_login': request.COOKIES['last_login'],
    }
    # return render(request, "wishlist.html")
    return render(request, "wishlist_ajax.html", context)

def show_create_wishlist(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        wishlist = BarangWishlist.objects.create(nama_barang=nama_barang,deskripsi=deskripsi,harga_barang=harga_barang)
        response = HttpResponseRedirect(reverse("wishlist:show_wishlist_ajax")) 
        return response

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}
<html lang="en">
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <nav class="navbar navbar-light bg-warning">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" style="font-family:'Courier New'"><strong>✨Welcome, {{nama}}✨</strong></a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active" style="font-family:'Courier New'"><a href="{% url 'wishlist:logout' %}"><strong>Log Out</strong></a></li>
            <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
          </ul>
        </div>
    </nav>
</head>

<body>
    <h5>Nama: </h5>
    <b>{{nama}}</b>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark"><tr class="table-info">
        <th class="table-info">Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr></thead>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}

        <tbody>
        {% for barang in list_barang %}
            <tr>
                <td>{{barang.nama_barang}}</td>
                <td>{{barang.harga_barang}}</td>
                <td>{{barang.deskripsi}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h5 style="font-family: 'Courier New'; padding: 5px;">Sesi terakhir login: {{ last_login }}</h5>
    <!-- <button><a href="{% url 'wishlist:logout' %}">Logout</a></button> -->
</body>
<style>
    body {
        margin: 15px;
        font-family: 'Courier New'; 
        padding: 5px; 
        margin: 10px;
        background-color:blanchedalmond;
    }
    table {
        margin-top: 10px;
    }
    li {
        margin-right: 10px;
    }
</style>
{% endblock content %}
</html>

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
<html lang="en">
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!-- AJAX IMPLEMENTATION-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
        // $("button").click(function(){
        $.get("/wishlist/json", function(datawishlist) {

            for (i=0;i<datawishlist.length;i++){

            $(".barang").append(`<tr><td>${datawishlist[i].fields.nama_barang}</td><td>${datawishlist[i].fields.harga_barang}</td><td>${datawishlist[i].fields.deskripsi}</td></tr>`)
        
            }

        });

        $("#submit_btn").click(function(){
        $.post("/wishlist/ajax/submit", {nama_barang: $("#nama_barang").val(),harga_barang:parseInt($("#harga_barang").val()),deskripsi:$("#deskripsi").val()} )
        $(".barang").append(`<tr><td>${$("#nama_barang").val()}</td><td>${$("#harga_barang").val()}</td><td>${$("#deskripsi").val()}</td></tr>`)
        })
        // });
    });
    </script>

    <nav class="navbar navbar-light bg-warning">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" style="font-family:'Courier New'"><strong>✨Welcome, {{nama}}✨</strong></a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active" style="font-family:'Courier New'"><a href="{% url 'wishlist:logout' %}"><strong>Log Out</strong></a></li>
            <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
          </ul>
        </div>
    </nav>
</head>
<form method="POST" action="" onsubmit="return false;">
    {% csrf_token %}
    <table>
      <tr>
        <td>Nama Barang:</td>
        <td>
          <input
            type="text"
            name="nama_barang"
            placeholder="Nama Barang"
            id="nama_barang"
            class="form-control"
          />
        </td>
      </tr>
  
      <tr>
        <td>Harga Barang:</td>
        <td>
          <input
            type="text"
            name="harga_barang"
            id="harga_barang"
            placeholder="Harga Barang"
            class="form-control"
          />
        </td>
      </tr>
      <tr>
        <td>Deskripsi:</td>
        <td>
          <input
            type="text"
            name="deskripsi"
            placeholder="Deskripsi"
            class="form-control"
            id="deskripsi"
          />
        </td>
      </tr>
  
      <tr>
        <td></td>
      <td>  <button id="submit_btn">Add new wishlist</button></td>    </tr>
    </table>
  </form>
  
<body>
    <h5>Nama: </h5>
    <b>{{nama}}</b>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark"><tr class="table-info">
        <th class="table-info">Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr></thead>
        {% comment %} Tambahkan datawishlist di bawah baris ini {% endcomment %}

        <tbody>
        {% for barang in list_barang %}
            <tr>
                <td>{{barang.nama_barang}}</td>
                <td>{{barang.harga_barang}}</td>
                <td>{{barang.deskripsi}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h5 style="font-family: 'Courier New'; padding: 5px;">Sesi terakhir login: {{ last_login }}</h5>
    <!-- <button><a href="{% url 'wishlist:logout' %}">Logout</a></button> -->
</body>
<style>
    body {
        margin: 15px;
        font-family: 'Courier New'; 
        padding: 5px; 
        margin: 10px;
        background-color:blanchedalmond;
    }
    table {
        margin-top: 10px;
    }
    li {
        margin-right: 10px;
    }
</style>
{% endblock content %}
</html>